email=str(input("Enter Your Gmail: "))
pwd=str(input("Enter Your Password: "))
tmail=str(input("Enter Your Target E-mail: "))
msg=str(input("Enter Your Message"))
amount=int(imput("Enter Your Amount"))
